# Copyright 2023 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Authors:
# - Thomas Benz <tbenz@iis.ee.ethz.ch>

header-regex: >
  (?:#\!/.*\n)*[/|#]+ Copyright ([0-9]+) [^\n]+\n(?:[/|#][^\n]*\n|\n)*?[/|#]+ SPDX-License-Identifier: (?:SHL-0\.51|Apache-2\.0)\n(?:[/|#][^\n]*\n|\n)*?[/|#]+ Authors:\n((?:[/|#]+ - [0-9A-Za-z .]+<[^\s>]+@[^\s>]+>\n)+)

author-regex: >
  ([0-9A-Za-z .]+)<([^\s>]+@[^\s>]+)>

excludes:
  - LICENSE
  - VERSION
  - CODEOWNERS
  - doc/fig/iDMA_overview
  - util/lint-commits.py
  - test/future/idma_tb_per2axi.sv
  - test/future/TLToAXI4.v

exclude-ext:
  - png
  - pyc
  - rst
  - svg
  - txt
  - json
  - toml
  - md
  - mdx
  - lock
  - local

exclude-paths:
  - target

allowed-years:
  - 2023
  - 2024
  - 2025
  - 2026

allowed-domains:
  - ethz.ch
  - mosaic-soc.com
