// Copyright 2026 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

// Authors:
// - Daniel Keller <dankeller@iis.ee.ethz.ch>

// AUTOGENERATED from the compute_op encode enum in idma_reg.rdl - do not edit.

<%
    enum = next(e for e in enums if e["name"] == "compute_op")
    width = enum["width"]
    name_w = max(len(m["name"]) for m in enum["choices"]) + len("COMPUTE_")
%>\
/// Compute operation selector
typedef enum logic [${width - 1}:0] {
% for m in enum["choices"]:
    ${("COMPUTE_" + m["name"]).ljust(name_w)} = ${width}'d${m["value"]}${"," if not loop.last else " "} // ${m["desc"]}
% endfor
} compute_op_e;
