// Copyright 2026 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

// Authors:
// - Daniel Keller <dankeller@iis.ee.ethz.ch>

// AUTOGENERATED from src/db/idma_inst64.yml - do not edit.
// The inst64 instruction encodings; the decode RTL is generated from the same file.
<%
    w = max(len(i['upper']) for i in insts) + len('IDMA_INST64__FUNCT7')
    iw = max(len(f['c']) for f in imm_fields) + len('IDMA_INST64_IMM__SHIFT')
    def insn(i):
        rd = '%[rd]' if i['writeback'] else 'x0'
        rs1 = '%[rs1]' if i['read'] & 1 else 'x0'
        rs2 = '%[rs2]' if i['read'] & 2 else 'x0'
        head = f'".insn r {opcode:#04x}, {funct3:#x}, {i["funct7"]:#04x}, {rd}, {rs1}, '
        if i['imm']:
            return f'{head}x" IDMA_INST64_STR(imm)'
        return f'{head}{rs2}"'
%>\

#ifndef IDMA_INST64_H_
#define IDMA_INST64_H_

/* ${description}: R-type on opcode ${f"{opcode:#04x}"}, funct3 ${funct3} */
#define ${'IDMA_INST64_OPCODE'.ljust(w)} ${f"{opcode:#04x}"}
#define ${'IDMA_INST64_FUNCT3'.ljust(w)} ${f"{funct3:#x}"}

/* Fields of the 5-bit immediate in the rs2 slot, relative to the immediate */
#define ${'IDMA_INST64_IMM_SHIFT'.ljust(iw)} ${imm_lsb}
% for f in imm_fields:
#define ${('IDMA_INST64_IMM_' + f['c'] + '_SHIFT').ljust(iw)} ${f['lsb']}
#define ${('IDMA_INST64_IMM_' + f['c'] + '_WIDTH').ljust(iw)} ${f['width']}
#define ${('IDMA_INST64_IMM_' + f['c'] + '_MASK').ljust(iw)} ${f"{f['mask']:#x}"}u
% endfor

/* Encodings; an instruction word is one iff (insn & _MASK) == _MATCH */
% for i in insts:
#define ${('IDMA_INST64_' + i['upper'] + '_FUNCT7').ljust(w)} ${f"{i['funct7']:#04x}"}
#define ${('IDMA_INST64_' + i['upper'] + '_MATCH').ljust(w)} ${f"{i['match']:#010x}"}u
#define ${('IDMA_INST64_' + i['upper'] + '_MASK').ljust(w)} ${f"{i['mask']:#010x}"}u
% endfor

/* Inline-asm templates for toolchains without the mnemonics. Operands are named [rd], [rs1],
 * [rs2]; `imm` must be a literal 0..31, e.g. IDMA_INST64_DMCPYI_INSN(6). */
#define IDMA_INST64_STR_(x) #x
#define IDMA_INST64_STR(x)  IDMA_INST64_STR_(x)
% for i in insts:
<%
    ops = []
    if i['rd']:
        ops.append(f"rd: {i['rd']}")
    for slot, desc in i['sources'].items():
        ops.append(f'{slot}: {desc}')
    if i['imm']:
        ops.append(f"imm: {i['imm_desc']}")
    macro = 'IDMA_INST64_' + i['upper'] + '_INSN' + ('(imm)' if i['imm'] else '')
%>\
/* ${i['upper']} (${i['kind']}${', needs ' + i['requires'] if i['requires'] else ''}); ${'; '.join(ops)} */
#define ${macro} ${insn(i)}
% endfor

#endif  /* IDMA_INST64_H_ */
