// Copyright 2026 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

// Authors:
// - Daniel Keller <dankeller@iis.ee.ethz.ch>

// AUTOGENERATED from src/db/idma_dmopc.yml - do not edit.
// The DMOPC contract of the inst64 frontend; the decode RTL is generated from the same file.
<%
    opc_w = max(len(o['c']) for o in opcodes + setters) + len('IDMA_DMOPC_OPC_')
    fld_w = max([len(f['c']) for f in fields] + [len(s['c']) + 5 for s in setters])
    fld_w += len('IDMA_DMOPC__SHIFT')
%>\

#ifndef IDMA_COMPUTE_H_
#define IDMA_COMPUTE_H_

/* Opcode bytes, placed in the DMOPC opcode field of the operand below */
% for o in opcodes + setters:
#define ${('IDMA_DMOPC_OPC_' + o['c']).ljust(opc_w)} 0x${o['hex']}
% endfor

/* Setter values: the fields concatenated, most significant first, in units of 1 << _UNIT_LOG2 */
% for s in setters:
#define ${('IDMA_DMOPC_' + s['c'] + '_UNIT_LOG2').ljust(fld_w)} ${s['shift']}
% endfor

/* Operand field positions; ${', '.join(f'{o} is {s}' for o, s in operands.items())} */
% for f in fields:
#define ${('IDMA_DMOPC_' + f['c'] + '_SHIFT').ljust(fld_w)} ${f['lsb']}
#define ${('IDMA_DMOPC_' + f['c'] + '_WIDTH').ljust(fld_w)} ${f['width']}
#define ${('IDMA_DMOPC_' + f['c'] + '_MASK').ljust(fld_w)} 0x${f['mask']}u
% endfor

#endif  /* IDMA_COMPUTE_H_ */
