# Copyright 2026 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Authors:
# - Daniel Keller <dankeller@iis.ee.ethz.ch>

# AUTOGENERATED from iDMA src/db/idma_inst64.yml - do not edit.
<%
    lo = opcode & 0x3
    hi = opcode >> 2
    def line(i):
        zeros = ' '.join(i['zeros'])
        args = ' '.join(i['args'])
        var = (args.ljust(20 - len(zeros)) + zeros) if zeros else args.ljust(20)
        return (f"{i['name'].ljust(8)}{var} 31..25={i['funct7']} 14..12={funct3} "
                f"6..2=0x{hi:02X} 1..0=0x{lo:X}")
%>\
# ${description}

% if note:
# INFO: ${note}

% endif
% for i in insts:
${line(i)}
% endfor
