# Copyright 2022 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Author: Thomas Benz <tbenz@iis.ee.ethz.ch>

variables:
  SPHINXBUILD: "/home/tbenz/.local/bin/sphinx-build"
  MORTY: "/home/tbenz/.cargo/bin/morty"

before_script:
  - source ~paulsc/.bashrc

stages:
  - prepare-non-free
  - iDMA

############# Below: only works on IIS machines ####################

prepare-non-free:
  stage: prepare-non-free
  script:
    - git clone git@iis-git.ee.ethz.ch:bslk/idma/idma-non-free.git
    - cd idma-non-free
    - git checkout deploy
    - make -B gen_sub_ci
  artifacts:
      paths:
        - idma-non-free/ci/*.yml


# Below: Automatically generated by util/gen_ci.py
