// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

`include "common_cells/assertions.svh"

/// Gates read-address requests according to the free space in the byte-lane data FIFOs.
///
/// The dataflow buffer consists of `StrbWidth` independent byte-wide FIFOs.  Accepting a
/// read-address request reserves one FIFO entry for every byte that the corresponding response
/// will place into a lane.  Entries are released when bytes leave the dataflow buffer.
///
/// Requests with deadlock-free operation disabled bypass the capacity check, but are still
/// accounted for.  Consequently, changing the mode between pipelined requests does not lose
/// track of previously reserved entries.
module idma_read_reservation_gate #(
  /// Number of byte lanes in the data path; must be a power of two.
  parameter int unsigned StrbWidth     = 32'd2,
  /// Number of entries in each byte-lane FIFO.
  parameter int unsigned BufferDepth   = 32'd3,
  /// Maximum number of read-address requests that may be in flight.
  parameter int unsigned NumAxInFlight = 32'd2,
  /// Type used for the byte count of one legalized read request.
  parameter type         len_t         = logic,
  /// Type used for the first byte lane of one legalized read request.
  parameter type         lane_t        = logic
) (
  input logic clk_i,
  input logic rst_ni,

  /// Read-address handshake from the reservation FIFO.
  input  logic ar_valid_i,
  output logic ar_ready_o,
  /// Read-address handshake toward the protocol-specific read module.
  output logic ar_valid_o,
  input  logic ar_ready_i,

  /// Number of response bytes generated by the current read-address request.
  input len_t  num_bytes_i,
  /// Byte lane receiving the first response byte.
  input lane_t start_lane_i,
  /// Enable capacity-based request admission for the current request.
  input logic  deadlock_free_i,

  /// One bit per byte-lane FIFO, asserted when an entry is popped.
  input logic [StrbWidth-1:0] buffer_pop_i
);

  localparam int unsigned LaneWidth = $clog2(StrbWidth);
  // Unsafe requests may temporarily reserve more than BufferDepth entries.  Size the
  // accounting state for the maximum byte count across all in-flight requests.
  localparam int unsigned UsageWidth = $bits(len_t) + $clog2(NumAxInFlight + 1);

  typedef logic [LaneWidth-1:0] lane_idx_t;
  typedef logic [UsageWidth-1:0] usage_t;

  lane_idx_t                 byte_remainder;
  len_t                      complete_lane_rows;

  usage_t    [StrbWidth-1:0] lane_usage;
  usage_t    [StrbWidth-1:0] lane_reservation;
  usage_t    [StrbWidth-1:0] lane_addition;
  usage_t    [StrbWidth-1:0] lane_removal;
  usage_t    [StrbWidth-1:0] counter_delta;

  logic      [StrbWidth-1:0] lane_fits;
  logic      [StrbWidth-1:0] counter_enable;
  logic      [StrbWidth-1:0] counter_down;
  logic      [StrbWidth-1:0] counter_overflow;
  logic                      request_allowed;
  logic                      ar_handshake;

  // StrbWidth is a power of two, so division and modulo reduce to slicing and shifting.
  assign complete_lane_rows = num_bytes_i >> LaneWidth;
  assign byte_remainder     = lane_idx_t'(num_bytes_i);

  always_comb begin : calculate_lane_reservations
    for (int unsigned lane = 0; lane < StrbWidth; lane++) begin
      lane_idx_t                lane_distance;
      logic      [UsageWidth:0] projected_usage;
      logic      [UsageWidth:0] available_capacity;

      // Count the response bytes assigned to this lane.  Subtraction in lane_idx_t
      // intentionally wraps modulo StrbWidth.
      lane_distance = lane_idx_t'(lane) - lane_idx_t'(start_lane_i);
      lane_reservation[lane] = usage_t'(complete_lane_rows) +
          usage_t'(lane_distance < byte_remainder);

      // A pop in the current cycle frees an entry in time for the accepted request.
      projected_usage = {1'b0, lane_usage[lane]} + {1'b0, lane_reservation[lane]};
      available_capacity = (UsageWidth + 1)'(BufferDepth);
      // The following line would save a cycle but make ar_valid dependent on w_ready, which
      // produces a combinational loop, which we don't want.
      // available_capacity = available_capacity + buffer_pop_i[lane];
      lane_fits[lane] = projected_usage <= available_capacity;
    end
  end

  // Allow a request to propagate if safe mode is turned off or if all lanes have space for the
  // bytes they will receive.
  assign request_allowed = ~deadlock_free_i | &lane_fits;
  assign ar_valid_o      = ar_valid_i & request_allowed;
  assign ar_ready_o      = ar_ready_i & request_allowed;
  assign ar_handshake    = ar_valid_o & ar_ready_i;

  // Account for accepted read requests and consumed bytes in one delta update per lane.
  always_comb begin : calculate_counter_updates
    for (int unsigned lane = 0; lane < StrbWidth; lane++) begin
      lane_addition[lane]  = ar_handshake ? lane_reservation[lane] : '0;
      lane_removal[lane]   = usage_t'(buffer_pop_i[lane]);
      counter_enable[lane] = lane_addition[lane] != lane_removal[lane];
      counter_down[lane]   = lane_addition[lane] < lane_removal[lane];
      if (counter_down[lane]) begin
        // Lane_removal is at most 1, so if lane_addition < lane_removal, count down by 1
        counter_delta[lane] = usage_t'(1);
      end else begin
        // Reserve as many bytes as will be pushed into the lane.
        counter_delta[lane] = lane_addition[lane] - lane_removal[lane];
      end
    end
  end

  for (genvar lane = 0; lane < StrbWidth; lane++) begin : gen_lane_usage_counters
    delta_counter #(
      .WIDTH(UsageWidth)
    ) i_lane_usage_counter (
      .clk_i,
      .rst_ni,
      .clear_i   (1'b0),
      .en_i      (counter_enable[lane]),
      .load_i    (1'b0),
      .down_i    (counter_down[lane]),
      .delta_i   (counter_delta[lane]),
      .d_i       ('0),
      .q_o       (lane_usage[lane]),
      .overflow_o(counter_overflow[lane])
    );

    `ASSERT(NoLaneUsageUnderflow, !counter_down[lane] || counter_delta[lane] <= lane_usage[lane],
            clk_i, !rst_ni, "A byte-lane data FIFO popped an entry that was not reserved")
    `ASSERT(NoLaneUsageOverflow, !counter_overflow[lane], clk_i, !rst_ni,
            "The read reservation counter overflowed")
    `ASSERT(SafeRequestFitsBuffer,
            ar_valid_i && deadlock_free_i |-> lane_reservation[lane] <= usage_t'(BufferDepth),
            clk_i, !rst_ni,
            "A deadlock-free read request requires more entries than one byte-lane FIFO holds")
  end

  `ASSERT_INIT(StrbWidthAtLeastTwo, StrbWidth >= 2, "StrbWidth must be at least two bytes")
  `ASSERT_INIT(StrbWidthPowerOfTwo, 2 ** LaneWidth == StrbWidth, "StrbWidth must be a power of two")
  `ASSERT_INIT(BufferDepthPositive, BufferDepth > 0, "BufferDepth must be greater than zero")
  `ASSERT_INIT(NumAxInFlightPositive, NumAxInFlight > 0, "NumAxInFlight must be greater than zero")
  `ASSERT_INIT(StartLaneWidthMatches, $bits(lane_t) == LaneWidth,
               "lane_t must encode exactly one byte-lane index")

  `ASSERT(NonZeroReadLength, ar_handshake |-> num_bytes_i != '0, clk_i, !rst_ni,
          "Accepted read-address requests must reserve at least one response byte")

  // CombinedShifter=0 does not imply start_lane_i=0 for every burst.  The first burst starts
  // at lane zero, while later legalized bursts can retain a non-zero source offset so the
  // fixed read shifter preserves the byte-stream position.

endmodule
