// Copyright 2026 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

// Authors:
// - Daniel Keller <dankeller@iis.ee.ethz.ch>

// AUTOGENERATED from src/db/idma_dmopc.yml - do not edit.
// Included in the body of `idma_inst64_compute_pkg`, hence no include guard.
<%
    opc_w = max(len(o['sv']) for o in opcodes)
    args = ', '.join(f'logic [{operand_width-1}:0] {s}' for s in operands.values())
    def call(opc):
        zeros = [f'{operand_width}\'b0'] * (len(operands) - 1)
        return ', '.join([f'{operand_width}\'({opc})'] + zeros)
    known = [o for o in opcodes if not o['enable']]
    pairs = [p for fl in operand_fields.values() for p in zip(fl, fl[1:])]
    layout = ', '.join(f'`{o}` is `data_{s}`' for o, s in operands.items())
%>\

/// DMOPC opcode byte width
localparam int unsigned OpcodeWidth = 32'd${opcode_width};

/// Opcode bytes; the gaps are reserved for ops not implemented in this backend family
% for o in opcodes:
localparam logic [OpcodeWidth-1:0] ${o['sv'].ljust(opc_w)} = ${opcode_width}'h${o['hex']};
% endfor

/// DMOPC operand layout; ${layout}
% for f in fields:
localparam int unsigned ${(f['sv'] + 'Lsb').ljust(name_width)} = 32'd${f['lsb']};
localparam int unsigned ${(f['sv'] + 'Width').ljust(name_width)} = ${f['width']};
% endfor

/// An RV32 core sign-extends the operands into their upper half; no field may cross it
localparam bit LayoutRv32Safe =
% for f in fields:
    (${f['sv']}Lsb + ${f['sv']}Width <= 32'd32)${' &&' if not loop.last else ';'}
% endfor

/// Fields sharing an operand must not overlap
localparam bit LayoutDisjoint =
% if pairs:
%   for lo, hi in pairs:
    (${lo['sv']}Lsb + ${lo['sv']}Width <= ${hi['sv']}Lsb)${' &&' if not loop.last else ';'}
%   endfor
% else:
    1'b1;
% endif

/// Decode the DMOPC operands; an unknown byte decodes to a plain copy and is asserted on.
function automatic idma_pkg::compute_options_t opc_decode(${args});
    idma_pkg::compute_options_t cmp;
    logic [OpcodeWidth-1:0]     opc;
    cmp = '0;
    opc = ${opcode_field['signal']}[${opcode_field['sv']}Lsb +: ${opcode_field['sv']}Width];
    unique case (opc)
% for o in opcodes:
%   if o['enable']:
        ${o['sv']}: begin
            cmp.enable = 1'b1;
            cmp.op     = idma_pkg::COMPUTE_${o['op']};
%     for p in o['params']:
<%
        lhs = f"            cmp.params.{p['target']} = "
        rhs = f"{p['field']['signal']}[{p['field']['sv']}Lsb +: {p['field']['sv']}Width];"
%>\
%       if len(lhs) + len(rhs) <= 100:
${lhs}${rhs}
%       else:
${lhs.rstrip()}
                ${rhs}
%       endif
%     endfor
        end
%   endif
% endfor
        default: cmp = '0;
    endcase
    return cmp;
endfunction

/// Is the opcode byte decodable on this implementation?
function automatic logic opc_known(logic [OpcodeWidth-1:0] opc);
    idma_pkg::compute_options_t cmp;
    cmp = opc_decode(${call('opc')});
    return ${''.join(f"(opc == {o['sv']}) | " for o in known)}cmp.enable;
endfunction

/// `idma_pkg::compute_op_e` encoding space; a value of it is also the all-mapped sentinel
localparam int unsigned NumComputeOpValues = 1 << $bits(idma_pkg::compute_op_e);
localparam int unsigned NumOpcodes         = 1 << OpcodeWidth;

/// Lowest `idma_pkg::compute_op_e` value that `opc_decode` reaches for no opcode byte
function automatic int unsigned first_unmapped_op();
    logic [NumComputeOpValues-1:0] reached;
    idma_pkg::compute_options_t    cmp;
    reached = '0;
    for (int unsigned b = 0; b < NumOpcodes; b++) begin
        cmp = opc_decode(${call('b')});
        reached[cmp.op] = 1'b1;
    end
    for (int unsigned v = 0; v < NumComputeOpValues; v++) begin
        if (idma_pkg::ComputeOpValid[v] & ~reached[v]) return v;
    end
    return NumComputeOpValues;
endfunction

localparam int unsigned UnmappedComputeOp = first_unmapped_op();
localparam bit          ComputeOpsMapped  = UnmappedComputeOp == NumComputeOpValues;
