// Copyright 2026 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

// Authors:
// - Daniel Keller <dankeller@iis.ee.ethz.ch>

// AUTOGENERATED from src/db/idma_inst64.yml - do not edit.
// Included in the body of `idma_inst64_snitch_pkg`, hence no include guard.
<%
    name_w = max(len(i['sv']) for i in insts) + len('Match')
    imm_w = max(len(f['sv']) for f in imm_fields) + len('Width')
%>\

/// Encodings as casez patterns; `?` marks an operand bit
% for i in insts:
localparam logic [31:0] ${i['upper'].ljust(name_w)} = 32'b${i['pattern']};
% endfor

/// An instruction word `instr` is one of these iff `(instr & <Name>Mask) == <Name>Match`
% for i in insts:
localparam logic [31:0] ${(i['sv'] + 'Match').ljust(name_w)} = 32'h${f"{i['match']:08x}"};
localparam logic [31:0] ${(i['sv'] + 'Mask').ljust(name_w)} = 32'h${f"{i['mask']:08x}"};
% endfor

/// The 5-bit immediate some instructions carry in the rs2 slot; positions in the instruction word
localparam int unsigned ${'ImmLsb'.ljust(imm_w)} = 32'd${imm_lsb};
localparam int unsigned ${'ImmWidth'.ljust(imm_w)} = 32'd5;
% for f in imm_fields:
localparam int unsigned ${(f['sv'] + 'Lsb').ljust(imm_w)} = 32'd${imm_lsb + f['lsb']};
localparam int unsigned ${(f['sv'] + 'Width').ljust(imm_w)} = 32'd${f['width']};
% endfor

/// Coprocessor-interface attributes of one instruction
typedef struct packed {
    /// One of the encodings above
    logic       known;
    /// Source registers read, {rs3, rs2, rs1}
    logic [2:0] register_read;
    /// Writes rd
    logic       writeback;
    /// Latches frontend configuration
    logic       stateful;
    /// Starts a transfer
    logic       launch;
    /// Reads frontend status
    logic       status;
    /// Carries the 5-bit immediate, and with it the channel
    logic       imm;
    /// Exists only with the on-the-fly compute datapath
    logic       req_compute;
    /// Exists only with the INIT read port
    logic       req_init;
} attr_t;

/// Attributes of `instr`; all zero for an encoding outside this instruction set
function automatic attr_t inst_attr(logic [31:0] instr);
    attr_t attr;
    attr = '0;
% for i in insts:
    ${'if' if loop.first else 'end else if'} ((instr & ${i['sv']}Mask) == ${i['sv']}Match) begin
        attr.known         = 1'b1;
        attr.register_read = 3'b${f"{i['read']:03b}"};
        attr.writeback     = 1'b${int(i['writeback'])};
        attr.stateful      = 1'b${int(i['kind'] == 'config')};
        attr.launch        = 1'b${int(i['kind'] == 'launch')};
        attr.status        = 1'b${int(i['kind'] == 'status')};
        attr.imm           = 1'b${int(i['imm'])};
        attr.req_compute   = 1'b${int(i['requires'] == 'compute')};
        attr.req_init      = 1'b${int(i['requires'] == 'init')};
% endfor
    end
    return attr;
endfunction
