#!/usr/bin/env python3
# Copyright 2026 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Authors:
# - Daniel Keller <dankeller@iis.ee.ethz.ch>

"""Render idma_pkg's compute collateral from the SystemRDL reg description.

The compute op encoding is defined once, in idma_reg.rdl (the compute_cfg.compute_op
encode enum); this emits the matching SV enum for idma_pkg.sv to `include, so the
package and the generated SW headers share one source. Output goes to stdout.
"""

import sys

from systemrdl import RDLCompiler


def main():
    rdl_file = sys.argv[1]
    rdlc = RDLCompiler()
    rdlc.compile_file(rdl_file)
    root = rdlc.elaborate()

    field = None
    for node in root.descendants():
        if node.get_path().endswith("compute_cfg.compute_op"):
            field = node
            break
    if field is None:
        sys.exit(f"{rdl_file}: compute_cfg.compute_op field not found")
    encode = field.get_property("encode")
    if encode is None:
        sys.exit(f"{rdl_file}: compute_op field has no encode enum")

    width = field.width
    members = [(m.name.upper(), m.value, m.rdl_desc) for m in encode]
    name_w = max(len(n) for n, _, _ in members) + len("COMPUTE_")

    print("// Copyright 2026 ETH Zurich and University of Bologna.")
    print("// Solderpad Hardware License, Version 0.51, see LICENSE for details.")
    print("// SPDX-License-Identifier: SHL-0.51")
    print("//")
    print("// AUTOGENERATED by util/gen_compute_svh.py from the compute_op encode enum")
    print(f"// in {rdl_file.split('/src/')[-1] if '/src/' in rdl_file else rdl_file}"
          " - do not edit.")
    print()
    print("/// Compute operation selector")
    print(f"typedef enum logic [{width - 1}:0] {{")
    for i, (name, value, desc) in enumerate(members):
        sep = "," if i < len(members) - 1 else " "
        print(f"    {'COMPUTE_' + name:<{name_w}} = {width}'d{value}{sep} // {desc}")
    print("} compute_op_e;")


if __name__ == "__main__":
    main()
