// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package dma_frontend_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 6;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [63:0] q;
  } dma_frontend_reg2hw_src_addr_reg_t;

  typedef struct packed {
    logic [63:0] q;
  } dma_frontend_reg2hw_dst_addr_reg_t;

  typedef struct packed {
    logic [63:0] q;
  } dma_frontend_reg2hw_num_bytes_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } decouple;
    struct packed {
      logic        q;
    } deburst;
    struct packed {
      logic        q;
    } serialize;
  } dma_frontend_reg2hw_conf_reg_t;

  typedef struct packed {
    logic [63:0] q;
    logic        re;
  } dma_frontend_reg2hw_next_id_reg_t;

  typedef struct packed {
    logic [63:0] q;
    logic        re;
  } dma_frontend_reg2hw_done_reg_t;

  typedef struct packed {
    logic        d;
  } dma_frontend_hw2reg_status_reg_t;

  typedef struct packed {
    logic [63:0] d;
  } dma_frontend_hw2reg_next_id_reg_t;

  typedef struct packed {
    logic [63:0] d;
  } dma_frontend_hw2reg_done_reg_t;

  // Register -> HW type
  typedef struct packed {
    dma_frontend_reg2hw_src_addr_reg_t src_addr; // [324:261]
    dma_frontend_reg2hw_dst_addr_reg_t dst_addr; // [260:197]
    dma_frontend_reg2hw_num_bytes_reg_t num_bytes; // [196:133]
    dma_frontend_reg2hw_conf_reg_t conf; // [132:130]
    dma_frontend_reg2hw_next_id_reg_t next_id; // [129:65]
    dma_frontend_reg2hw_done_reg_t done; // [64:0]
  } dma_frontend_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    dma_frontend_hw2reg_status_reg_t status; // [128:128]
    dma_frontend_hw2reg_next_id_reg_t next_id; // [127:64]
    dma_frontend_hw2reg_done_reg_t done; // [63:0]
  } dma_frontend_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] DMA_FRONTEND_SRC_ADDR_OFFSET = 6'h 0;
  parameter logic [BlockAw-1:0] DMA_FRONTEND_DST_ADDR_OFFSET = 6'h 8;
  parameter logic [BlockAw-1:0] DMA_FRONTEND_NUM_BYTES_OFFSET = 6'h 10;
  parameter logic [BlockAw-1:0] DMA_FRONTEND_CONF_OFFSET = 6'h 18;
  parameter logic [BlockAw-1:0] DMA_FRONTEND_STATUS_OFFSET = 6'h 20;
  parameter logic [BlockAw-1:0] DMA_FRONTEND_NEXT_ID_OFFSET = 6'h 28;
  parameter logic [BlockAw-1:0] DMA_FRONTEND_DONE_OFFSET = 6'h 30;

  // Reset values for hwext registers and their fields
  parameter logic [0:0] DMA_FRONTEND_STATUS_RESVAL = 1'h 0;
  parameter logic [63:0] DMA_FRONTEND_NEXT_ID_RESVAL = 64'h 0;
  parameter logic [63:0] DMA_FRONTEND_DONE_RESVAL = 64'h 0;

  // Register index
  typedef enum int {
    DMA_FRONTEND_SRC_ADDR,
    DMA_FRONTEND_DST_ADDR,
    DMA_FRONTEND_NUM_BYTES,
    DMA_FRONTEND_CONF,
    DMA_FRONTEND_STATUS,
    DMA_FRONTEND_NEXT_ID,
    DMA_FRONTEND_DONE
  } dma_frontend_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] DMA_FRONTEND_PERMIT [7] = '{
    4'b 1111, // index[0] DMA_FRONTEND_SRC_ADDR
    4'b 1111, // index[1] DMA_FRONTEND_DST_ADDR
    4'b 1111, // index[2] DMA_FRONTEND_NUM_BYTES
    4'b 0001, // index[3] DMA_FRONTEND_CONF
    4'b 0001, // index[4] DMA_FRONTEND_STATUS
    4'b 1111, // index[5] DMA_FRONTEND_NEXT_ID
    4'b 1111  // index[6] DMA_FRONTEND_DONE
  };

endpackage

