# Copyright 2023 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Authors:
# - Paul Scheffler <paulsc@iis.ee.ethz.ch>
# - Thomas Benz <tbenz@iis.ee.ethz.ch>

name: analyze

on:
  push:
    branches-ignore:
      - '__deploy__**'
  pull_request:
    branches-ignore:
      - '__deploy__**'
  workflow_dispatch:
    branches-ignore:
      - '__deploy__**'

jobs:

  analyze-contributors:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Install Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.9'
          cache: 'pip'
    -
      name: Python Requirements
      run: pip install -r requirements.txt
    -
      name: List contributors
      run: scripts/list-contributors | tee contributions.txt
    -
      name: Upload contributions.txt
      uses: actions/upload-artifact@v4
      with:
        name: contributions
        path: contributions.txt
        retention-days: 7

  analyze-todos:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Install Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.9'
          cache: 'pip'
    -
      name: Python Requirements
      run: pip install -r requirements.txt
    -
      name: List todos
      run: scripts/list-todos | tee open_todos.txt
    -
      name: Upload todos.txt
      uses: actions/upload-artifact@v4
      with:
        name: open_todos
        path: open_todos.txt
        retention-days: 7
