# Copyright 2023 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Authors:
# - Paul Scheffler <paulsc@iis.ee.ethz.ch>
# - Thomas Benz <tbenz@iis.ee.ethz.ch>

name: build

on:
  workflow_call:
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        target: [hw, doc]
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Cache Bender database
        uses: ./.github/actions/bender-db-cache
      -
        name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      -
        name: Install RISC-V GCC toolchain
        uses: pulp-platform/pulp-actions/riscv-gcc-install@v2.5.0
        with:
          distro: ubuntu-22.04
          nightly-date: '2023.03.14'
          target: riscv64-elf
      -
        name: Setup Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
      -
        name: Install Bender
        uses: pulp-platform/pulp-actions/bender-install@v2.5.0
        with:
          version: 0.32.1
      -
        name: Check clean
        run: uv run --locked make idma_clean_all
      -
        name: Check whether clean
        run: git status && test -z "$(git status --porcelain --ignore-submodules)"
      -
        name: Build target
        run: uv run --locked make -j9 idma_${{ matrix.target }}_all
      -
        name: Check whether stale
        run: git status && test -z "$(git status --porcelain --ignore-submodules)"
