# Copyright 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Authors:
# - Thomas Benz <tbenz@iis.ee.ethz.ch>

name: deploy

on:
  workflow_call:
    inputs:
      IDMA_BACKEND_IDS:
        description: Backend variants to generate.
        required: false
        type: string
        default: "rw_axi r_obi_w_axi r_axi_w_obi rw_axi_rw_axis rw_obi r_obi_rw_init_w_axi r_axi_rw_init_rw_obi rw_axi_rw_init_rw_obi"
      IDMA_ADD_FE_IDS:
        description: Register frontend variants to generate.
        required: false
        type: string
        default: "reg32_4d reg64_4d"
      IDMA_REG_CPUIF:
        description: PeakRDL CPU interface used for generated register frontends.
        required: false
        type: string
        default: "apb4-flat"
  workflow_dispatch:
    inputs:
      IDMA_BACKEND_IDS:
        description: Backend variants to generate.
        required: false
        type: string
        default: "rw_axi r_obi_w_axi r_axi_w_obi rw_axi_rw_axis rw_obi r_obi_rw_init_w_axi r_axi_rw_init_rw_obi rw_axi_rw_init_rw_obi"
      IDMA_ADD_FE_IDS:
        description: Register frontend variants to generate.
        required: false
        type: string
        default: "reg32_4d reg64_4d"
      IDMA_REG_CPUIF:
        description: PeakRDL CPU interface used for generated register frontends.
        required: false
        type: string
        default: "apb4-flat"

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    -
      name: Checkout
      uses: actions/checkout@v5
      with:
          fetch-depth: 0
    -
      name: Cache Bender database
      uses: ./.github/actions/bender-db-cache
    -
      name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
          enable-cache: true
    -
      name: Install Bender
      uses: pulp-platform/pulp-actions/bender-install@v2.5.0
      with:
        version: 0.32.0
    -
      name: Build hardware
      run: |
        uv run --locked make -B idma_hw_all idma_sw_all \
          IDMA_BACKEND_IDS="${{ inputs.IDMA_BACKEND_IDS }}" \
          IDMA_REG_CPUIF="${{ inputs.IDMA_REG_CPUIF }}" \
          IDMA_ADD_FE_IDS="${{ inputs.IDMA_ADD_FE_IDS }}"
    -
      name: Deploy generated files
      run: |
        git config user.email "github-ci@iis.ee.ethz.ch"
        git config user.name "github-ci"
        git fetch --all
        uv run --locked python3 util/deploy.py
