# Copyright 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Authors:
# - Thomas Benz <tbenz@iis.ee.ethz.ch>

name: deploy

on:
  workflow_call:
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    -
      name: Cache Bender database
      uses: ./.github/actions/bender-db-cache
    -
      name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
          enable-cache: true
    -
      name: Install Bender
      uses: pulp-platform/pulp-actions/bender-install@v2.5.0
      with:
        version: 0.32.0
    -
      name: Build hardware
      run: uv run --locked make -B idma_hw_all
    -
      name: Deploy generated files
      run: |
        git config user.email "github-ci@iis.ee.ethz.ch"
        git config user.name "github-ci"
        git fetch --all
        uv run --locked python3 util/deploy.py
